# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-27 03:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('COM_StockCode', models.CharField(max_length=30, unique=True)),
                ('COM_Name', models.CharField(max_length=30)),
                ('COM_IssuedShare', models.CharField(max_length=30)),
                ('COM_ParCurrency', models.CharField(max_length=30)),
                ('COM_ParValue', models.CharField(max_length=30)),
                ('COM_Industry', models.CharField(max_length=30)),
                ('COM_Profile', models.CharField(max_length=30000)),
                ('COM_ListingDate', models.CharField(max_length=30)),
                ('COM_AuthCapital', models.CharField(max_length=30)),
                ('COM_IssuedCapital', models.CharField(max_length=30)),
                ('COM_BoardLot', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Ratio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RAT_LatestUpdate', models.DateTimeField(auto_created=True, auto_now=True)),
                ('RAT_Year', models.CharField(max_length=30)),
                ('RAT_CurrentRatio', models.CharField(max_length=30)),
                ('RAT_QuickRatio', models.CharField(max_length=30)),
                ('RAT_LTDebtEquity', models.CharField(max_length=30)),
                ('RAT_TotalDebtEquity', models.CharField(max_length=30)),
                ('RAT_TotalDebtCapital', models.CharField(max_length=30)),
                ('RAT_ROE', models.CharField(max_length=30)),
                ('RAT_ROC', models.CharField(max_length=30)),
                ('RAT_ROTA', models.CharField(max_length=30)),
                ('RAT_OPM', models.CharField(max_length=30)),
                ('RAT_PreTaxPM', models.CharField(max_length=30)),
                ('RAT_NetPM', models.CharField(max_length=30)),
                ('RAT_InventoryTurnover', models.CharField(max_length=30)),
                ('RAT_DividendPayout', models.CharField(max_length=30)),
                ('RAT_NP', models.CharField(max_length=30)),
                ('RAT_NPG', models.CharField(max_length=30)),
                ('RAT_EPS', models.CharField(max_length=30)),
                ('RAT_EPSGrowth', models.CharField(max_length=30)),
                ('RAT_DPS', models.CharField(max_length=30)),
                ('RAT_PE', models.CharField(max_length=30)),
                ('RAT_Yield', models.CharField(max_length=30)),
                ('RAT_NAV', models.CharField(max_length=30)),
                ('RAT_Currency', models.CharField(max_length=30)),
                ('RAT_COM_StockCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Technical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TEC_LatestUpdate', models.CharField(max_length=30)),
                ('TEC_ClosingPrice', models.CharField(max_length=30)),
                ('TEC_1MonthChange', models.CharField(max_length=30)),
                ('TEC_3MonthChange', models.CharField(max_length=30)),
                ('TEC_52WeekChange', models.CharField(max_length=30)),
                ('TEC_1MonthHSIRelative', models.CharField(max_length=30)),
                ('TEC_3MonthHSIRelative', models.CharField(max_length=30)),
                ('TEC_52WeekHSIRelative', models.CharField(max_length=30)),
                ('TEC_MarketCapital', models.CharField(max_length=30)),
                ('TEC_52WeekHigh', models.CharField(max_length=30)),
                ('TEC_52WeekLow', models.CharField(max_length=30)),
                ('TEC_1MonthAvgVol', models.CharField(max_length=30)),
                ('TEC_3MonthAvgVol', models.CharField(max_length=30)),
                ('TEC_10DayMovingAvg', models.CharField(max_length=30)),
                ('TEC_50DayMovingAvg', models.CharField(max_length=30)),
                ('TEC_90DayMovingAvg', models.CharField(max_length=30)),
                ('TEC_250DayMovingAvg', models.CharField(max_length=30)),
                ('TEC_14DayRSI', models.CharField(max_length=30)),
                ('TEC_COM_StockCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Company')),
            ],
        ),
    ]
