# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-27 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratio',
            name='RAT_COM_StockCode',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='technical',
            name='TEC_COM_StockCode',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
