# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-27 03:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20170527_0341'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='COM_LatestUpdate',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
        migrations.AlterField(
            model_name='technical',
            name='TEC_LatestUpdate',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
    ]
