# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_auto_20170531_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historial_Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HIS_COM_StockCode', models.IntegerField()),
                ('HIS_Date', models.CharField(max_length=30)),
                ('HIS_Open', models.IntegerField()),
                ('HIS_Low', models.IntegerField()),
                ('HIS_Close', models.IntegerField()),
                ('HIS_Adj_Close', models.IntegerField()),
                ('HIS_Volume', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='ratio',
            name='RAT_COM_StockCode',
            field=models.IntegerField(),
        ),
    ]
