# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_auto_20170601_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historical_price',
            name='HIS_Date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='ratio',
            name='RAT_Year',
            field=models.DateField(),
        ),
    ]
