# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_auto_20170603_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratio',
            name='RAT_COM_StockCode',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='ratio',
            name='RAT_Year',
            field=models.CharField(max_length=30),
        ),
    ]
