# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0012_auto_20170603_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='COM_StockCode',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='technical',
            name='TEC_COM_StockCode',
            field=models.CharField(max_length=10),
        ),
    ]
