# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-01 02:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0014_auto_20170608_0530'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='COM_AuthCapital',
            new_name='auth_capital',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='COM_BoardLot',
            new_name='board_lot',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='COM_Industry',
            new_name='industry',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='COM_IssuedCapital',
            new_name='issued_capital',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='COM_IssuedShare',
            new_name='issued_share',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='COM_LatestUpdate',
            new_name='latest_update',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='COM_ListingDate',
            new_name='listing_date',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='COM_Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='COM_ParCurrency',
            new_name='par_currency',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='COM_ParValue',
            new_name='par_value',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='COM_StockCode',
            new_name='stock_id',
        ),
        migrations.RenameField(
            model_name='historical_price',
            old_name='HIS_COM_StockCode',
            new_name='adj_close',
        ),
        migrations.RenameField(
            model_name='historical_price',
            old_name='HIS_Adj_Close',
            new_name='close',
        ),
        migrations.RenameField(
            model_name='historical_price',
            old_name='HIS_Date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='historical_price',
            old_name='HIS_Close',
            new_name='low',
        ),
        migrations.RenameField(
            model_name='historical_price',
            old_name='HIS_Low',
            new_name='open',
        ),
        migrations.RenameField(
            model_name='historical_price',
            old_name='HIS_Open',
            new_name='volume',
        ),
        migrations.RemoveField(
            model_name='company',
            name='COM_Profile',
        ),
        migrations.RemoveField(
            model_name='historical_price',
            name='HIS_Volume',
        ),
        migrations.AddField(
            model_name='company',
            name='profile',
            field=models.CharField(default=1, max_length=30000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historical_price',
            name='stock_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stock.Company'),
            preserve_default=False,
        ),
    ]
