# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-01 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0015_auto_20171001_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historical_price',
            name='adj_close',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='historical_price',
            name='close',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='historical_price',
            name='low',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='historical_price',
            name='open',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='historical_price',
            name='volume',
            field=models.IntegerField(null=True),
        ),
    ]
