# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 03:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0017_auto_20171001_0323'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equation',
            fields=[
                ('E_Name', models.CharField(auto_created=True, max_length=10, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('param1', models.CharField(max_length=50, null=True)),
                ('param2', models.CharField(max_length=50, null=True)),
                ('param3', models.CharField(max_length=50, null=True)),
                ('param4', models.CharField(max_length=50, null=True)),
                ('param5', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('model_id', models.CharField(auto_created=True, max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, null=True)),
                ('description', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Model_param',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param1', models.CharField(max_length=50, null=True)),
                ('param2', models.CharField(max_length=50, null=True)),
                ('param3', models.CharField(max_length=50, null=True)),
                ('param4', models.CharField(max_length=50, null=True)),
                ('param5', models.CharField(max_length=50, null=True)),
                ('e_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Equation')),
                ('model_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Model')),
            ],
        ),
        migrations.DeleteModel(
            name='Ratio',
        ),
        migrations.DeleteModel(
            name='Technical',
        ),
        migrations.RemoveField(
            model_name='company',
            name='auth_capital',
        ),
        migrations.RemoveField(
            model_name='company',
            name='id',
        ),
        migrations.RemoveField(
            model_name='company',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='company',
            name='issued_capital',
        ),
        migrations.RemoveField(
            model_name='company',
            name='issued_share',
        ),
        migrations.RemoveField(
            model_name='company',
            name='latest_update',
        ),
        migrations.RemoveField(
            model_name='company',
            name='listing_date',
        ),
        migrations.RemoveField(
            model_name='company',
            name='par_currency',
        ),
        migrations.RemoveField(
            model_name='company',
            name='par_value',
        ),
        migrations.RemoveField(
            model_name='company',
            name='profile',
        ),
        migrations.AlterField(
            model_name='company',
            name='board_lot',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='stock_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
