# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0019_model_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='model_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
