# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 06:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0020_auto_20171012_0341'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Equation',
            new_name='Indicator',
        ),
    ]
