# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0021_auto_20171012_0609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='model_param',
            name='e_name',
        ),
        migrations.RemoveField(
            model_name='model_param',
            name='model_id',
        ),
        migrations.AlterField(
            model_name='company',
            name='board_lot',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historical_price',
            name='adj_close',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historical_price',
            name='close',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historical_price',
            name='low',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historical_price',
            name='open',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historical_price',
            name='volume',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Indicator',
        ),
        migrations.DeleteModel(
            name='Model',
        ),
        migrations.DeleteModel(
            name='Model_param',
        ),
    ]
