# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-20 07:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0024_latestinfo_latestpriceinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ratio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('current_ratio', models.FloatField(blank=True, null=True)),
                ('div_payout', models.FloatField(blank=True, null=True)),
                ('fiscal_year_high', models.FloatField(blank=True, null=True)),
                ('fiscal_year_low', models.FloatField(blank=True, null=True)),
                ('fiscal_year_per_high', models.FloatField(blank=True, null=True)),
                ('fiscal_year_per_low', models.FloatField(blank=True, null=True)),
                ('fiscal_year_yield_high', models.FloatField(blank=True, null=True)),
                ('fiscal_year_yield_low', models.FloatField(blank=True, null=True)),
                ('inventory_turnover', models.FloatField(blank=True, null=True)),
                ('longterm_de', models.FloatField(blank=True, null=True)),
                ('npm', models.FloatField(blank=True, null=True)),
                ('opm', models.FloatField(blank=True, null=True)),
                ('pretax_pm', models.FloatField(blank=True, null=True)),
                ('quick_ratio', models.FloatField(blank=True, null=True)),
                ('roce', models.FloatField(blank=True, null=True)),
                ('roe', models.FloatField(blank=True, null=True)),
                ('rota', models.FloatField(blank=True, null=True)),
                ('total_de_employed', models.FloatField(blank=True, null=True)),
                ('total_de', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='latestinfo',
            name='stock_id',
        ),
        migrations.AddField(
            model_name='company',
            name='auth_capital',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='issued_capital',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='listing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='par_currency',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='par_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='profile',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='board_lot',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='LatestInfo',
        ),
        migrations.AddField(
            model_name='ratio',
            name='stock_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Company'),
        ),
    ]
