# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-14 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='filter',
            name='parameter',
            field=models.ManyToManyField(to='filter.Parameter'),
        ),
    ]
