# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 08:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0003_filterparam'),
    ]

    operations = [
        migrations.AddField(
            model_name='filterparam',
            name='param_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='filter.Parameter'),
            preserve_default=False,
        ),
    ]
