# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0004_filterparam_param_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filter',
            name='parameter',
        ),
        migrations.RemoveField(
            model_name='filterparam',
            name='id',
        ),
        migrations.AddField(
            model_name='filterparam',
            name='param_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='filterparam',
            name='operator',
            field=models.CharField(blank=True, choices=[('gt', '>'), ('gte', '>='), ('lt', '<'), ('lte', '<='), ('eq', '=')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='filterparam',
            name='value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
