# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0005_auto_20171016_0726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filterparam',
            name='param_id',
        ),
        migrations.AddField(
            model_name='filterparam',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
