# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 07:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0006_auto_20171016_0726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filterparam',
            name='operator',
        ),
    ]
