# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0007_remove_filterparam_operator'),
    ]

    operations = [
        migrations.AddField(
            model_name='filterparam',
            name='operator',
            field=models.CharField(blank=True, choices=[('gt', '>'), ('gte', '>='), ('lt', '<'), ('lte', '<='), ('eq', '=')], max_length=3, null=True),
        ),
    ]
