# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0008_filterparam_operator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filterparam',
            name='id',
        ),
        migrations.AddField(
            model_name='filterparam',
            name='param_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
