# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0010_parameter_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='data_table',
            field=models.CharField(choices=[('RATIO', 'RATIO'), ('TECHNICAL', 'TECHNICAL')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
