# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0011_parameter_data_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='attr_name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
