# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 21:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0022_auto_20171012_2125'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('e_name', models.CharField(auto_created=True, max_length=10, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('param1', models.CharField(blank=True, max_length=50, null=True)),
                ('param2', models.CharField(blank=True, max_length=50, null=True)),
                ('param3', models.CharField(blank=True, max_length=50, null=True)),
                ('param4', models.CharField(blank=True, max_length=50, null=True)),
                ('param5', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('model_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Model_param',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param1', models.CharField(blank=True, max_length=50, null=True)),
                ('param2', models.CharField(blank=True, max_length=50, null=True)),
                ('param3', models.CharField(blank=True, max_length=50, null=True)),
                ('param4', models.CharField(blank=True, max_length=50, null=True)),
                ('param5', models.CharField(blank=True, max_length=50, null=True)),
                ('e_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.Indicator')),
                ('model_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.Model')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('RunDate', models.DateTimeField(auto_now=True)),
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('Status', models.CharField(choices=[('running', 'running'), ('done', 'done')], max_length=10)),
                ('model_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.Model')),
            ],
        ),
        migrations.CreateModel(
            name='Report_stock_no',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.ManyToManyField(to='model.Report')),
                ('stock_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Company')),
            ],
        ),
    ]
