# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='creationDate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
