# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-14 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0003_auto_20171013_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='indicators',
            field=models.ManyToManyField(to='model.Indicator'),
        ),
    ]
