# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0004_model_indicators'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report_stock_no',
            name='report_id',
        ),
        migrations.RemoveField(
            model_name='report_stock_no',
            name='stock_id',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='param4',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='param5',
        ),
        migrations.RemoveField(
            model_name='model_param',
            name='param4',
        ),
        migrations.RemoveField(
            model_name='model_param',
            name='param5',
        ),
        migrations.AddField(
            model_name='report',
            name='description',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='result_stock_id',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.DeleteModel(
            name='Report_stock_no',
        ),
    ]
