# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 18:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0005_auto_20171021_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report_param',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param1', models.FloatField(blank=True, max_length=50, null=True)),
                ('param2', models.FloatField(blank=True, max_length=50, null=True)),
                ('param3', models.FloatField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='model_param',
            old_name='e_name',
            new_name='indicator',
        ),
        migrations.RenameField(
            model_name='model_param',
            old_name='model_id',
            new_name='model',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='dateCreated',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='e_name',
        ),
        migrations.RemoveField(
            model_name='model',
            name='indicators',
        ),
        migrations.RemoveField(
            model_name='model_param',
            name='id',
        ),
        migrations.RemoveField(
            model_name='report',
            name='description',
        ),
        migrations.AddField(
            model_name='indicator',
            name='name',
            field=models.CharField(auto_created=True, default=1, max_length=50, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='model_param',
            name='param_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report_param',
            name='e_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.Indicator'),
        ),
        migrations.AddField(
            model_name='report_param',
            name='report_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.Report'),
        ),
    ]
