# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-28 15:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0007_auto_20171026_0214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model_param',
            name='param1',
        ),
        migrations.RemoveField(
            model_name='model_param',
            name='param2',
        ),
        migrations.RemoveField(
            model_name='model_param',
            name='param3',
        ),
        migrations.AddField(
            model_name='model_param',
            name='compare_indicator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compare', to='model.Model'),
        ),
        migrations.AddField(
            model_name='model_param',
            name='operator',
            field=models.CharField(blank=True, choices=[('gt', '>'), ('gte', '>='), ('lt', '<'), ('lte', '<='), ('eq', '=')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='model_param',
            name='param_type',
            field=models.CharField(choices=[('value', 'value'), ('indicator', 'indicator')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='model_param',
            name='value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
