# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-28 16:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0008_auto_20171028_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_param',
            name='indicator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='model.Indicator'),
        ),
        migrations.AlterField(
            model_name='model_param',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='model.Model'),
        ),
        migrations.AlterField(
            model_name='model_param',
            name='param_type',
            field=models.CharField(blank=True, choices=[('value', 'value'), ('indicator', 'indicator')], max_length=10, null=True),
        ),
    ]
