# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0009_auto_20171028_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report_param',
            name='e_name',
        ),
        migrations.RemoveField(
            model_name='report_param',
            name='report_id',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='model_id',
            new_name='model',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='RunDate',
            new_name='rundate',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='Status',
            new_name='status',
        ),
        migrations.AddField(
            model_name='model_param',
            name='ci_param1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='model_param',
            name='ci_param2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='model_param',
            name='ci_param3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='model_param',
            name='i_param1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='model_param',
            name='i_param2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='model_param',
            name='i_param3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='model_param',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.DeleteModel(
            name='Report_param',
        ),
    ]
