# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-01 01:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0010_auto_20171031_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_param',
            name='compare_indicator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compare', to='model.Indicator'),
        ),
        migrations.AlterField(
            model_name='report',
            name='rundate',
            field=models.DateTimeField(),
        ),
    ]
