# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-01 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0011_auto_20171101_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='function',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
