# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-09 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0025_auto_20171020_0708'),
        ('model', '0013_report_result_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='backtesting_stock',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('stocks', models.ManyToManyField(to='stock.Company')),
            ],
        ),
    ]
