# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-09 21:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0014_backtesting_stock'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='backtesting_stock',
            new_name='Backtest_stock_list',
        ),
    ]
