# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-09 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0015_auto_20171110_0531'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_param',
            name='eq_diff',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
