# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-11 10:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0016_model_param_eq_diff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backtest_stock_list',
            name='stocks',
        ),
        migrations.DeleteModel(
            name='Backtest_stock_list',
        ),
    ]
