# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-12 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0017_auto_20171111_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_param',
            name='operator',
            field=models.CharField(blank=True, choices=[('>', '>'), ('>=', '>='), ('<', '<'), ('<=', '<='), ('=', '=')], max_length=3, null=True),
        ),
    ]
