# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-11 12:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='backtest',
            old_name='model_id',
            new_name='backtest_id',
        ),
    ]
