# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-11 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0002_auto_20171111_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtest',
            name='enddate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backtest',
            name='startdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
