# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-11 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0003_auto_20171112_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtest',
            name='capital',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
