# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-12 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0005_auto_20171112_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtest_param',
            name='trigger',
            field=models.NullBooleanField(),
        ),
    ]
