# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-12 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0006_backtest_param_trigger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backtest_param',
            name='trigger',
            field=models.BooleanField(default=False),
        ),
    ]
