# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-12 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0007_auto_20171112_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtest_param',
            name='period',
            field=models.CharField(choices=[('daily', 'daily'), ('weekly', 'weekly'), ('monthly', 'monthly')], default='daily', max_length=20),
            preserve_default=False,
        ),
    ]
